# This file was generated by the {rix} R package v0.4.1 on 2023-10-27
# with following call:
# >rix(r_ver = "976fa3369d722e76f37c77493d99829540d43845",
#  > r_pkgs = c("dplyr",
#  > "janitor",
#  > "AER",
#  > "targets",
#  > "tarchetypes",
#  > "rmarkdown"),
#  > system_pkgs = c("quarto"),
#  > git_pkgs = list(list(package_name = "housing",
#  > repo_url = "https://github.com/rap4all/housing/",
#  > branch_name = "fusen",
#  > commit = "1c860959310b80e67c41f7bbdc3e84cef00df18e")),
#  > ide = c("rstudio",
#  > "other",
#  > "code")[2],
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = "")
# It uses nixpkgs' revision 976fa3369d722e76f37c77493d99829540d43845 for reproducibility purposes
# which will install R version 4.3.1
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/976fa3369d722e76f37c77493d99829540d43845.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) dplyr janitor AER targets tarchetypes rmarkdown;
};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "housing";
    src = pkgs.fetchgit {
      url = "https://github.com/rap4all/housing/";
      branchName = "fusen";
      rev = "1c860959310b80e67c41f7bbdc3e84cef00df18e";
      sha256 = "sha256-s4KGtfKQ7hL0sfDhGb4BpBpspfefBN6hf+XlslqyEn4=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) dplyr ggplot2 janitor purrr readxl rlang rvest stringr tidyr;
    };
  }) ];
  system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocalesUtf8 quarto;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocalesUtf8}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ git_archive_pkgs rpkgs  system_packages  ];
      
  }
