
# https://github.com/b-rodrigues/rix#returning-users
# It should be noted that as of September 2023, 
# **RStudio is not available for macOS through Nix **
# so the expression generated by the call above will not build successfully.
# It is also not possible to use RStudio installed by other means
# with a Nix environment. 
# This is because RStudio changes some default environment variables 
# and a globally installed RStudio 
# (the one you install normally) 
# would not recognize the R installed in the Nix environment. 

library(rix)

(path_default_nix <- ".") # tempdir())

# https://b-rodrigues.github.io/rix/articles/building-reproducible-development-environments-with-rix.html
# RStudio looks for R in predefined paths and cannot “see” the R provided by a Nix environment, it will instead use the version installed on your machine. This means that if you use RStudio to work interactively with R, you will need to install RStudio inside that environment. rix::rix() can generate a default.nix file that does that.


# /Users/johngavin/Library/R/arm64/4.3/library 835 packages
# /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library 29 package


#  all features of {rix} 
# https://b-rodrigues.github.io/rix/articles/building-reproducible-development-environments-with-rix.html#a-complete-example
rix(r_ver = "4.3.1",
    r_pkgs = c("dplyr", "janitor", "AER", # "AER@1.2-8",
               "targets", "tarchetypes", "rmarkdown"
               ),
    system_pkgs = c("quarto"),
    git_pkgs = list(
      list(package_name = "housing",
           repo_url = "https://github.com/rap4all/housing/",
           branch_name = "fusen",
           commit = "1c860959310b80e67c41f7bbdc3e84cef00df18e")
      # list(package_name = "fusen",
      #      repo_url = "https://github.com/ThinkR-open/fusen",
      #      branch_name = "main",
      #      commit = "d617172447d2947efb20ad6a4463742b8a5d79dc"),
    ),
    ide = c("other", "code")[2], # "rstudio", 
    project_path = path_default_nix,
    # run a {targets} pipeline each time I dropped into the shell
    # https://www.brodrigues.co/blog/2023-08-12-nix_for_r_part4/
    shell_hook = "",
    print = FALSE,
    overwrite = TRUE)
file.edit("./default.nix")
nix_build(project_path = ".", exec_mode = c("blocking", "non-blocking"))
rix::nix_build()

"
# https://nixos.wiki/wiki/Cleaning_the_nix_store
nix-store --gc
nix-collect-garbage --delete-old # nix-collect-garbage --help
sudo nix-store --verify --check-contents --repair
nix-store --delete /nix/store/hg49x1gdlg3d7wmxgakdyr93jixa2v6y-RStudio-2022.07.1+554-wrapper.drv

nix-store --gc --print-roots | egrep -v '^(/nix/var|/run/\w+-system|\{memory|/proc)'

export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
nix-build --impure
nix-shell
rstudio
" -> tmp ; rm(tmp)

# https://github.com/b-rodrigues/rix#returning-users
file.copy(
  # default.nix is the file containing the Nix expression
  from = system.file("extdata", "default.nix", package = "rix"),
  to = ".", overwrite = TRUE
)
# nix_build() is a wrapper around the command line tool `nix-build`
nix_build(project_path = ".")
# nix-shell to start R

# basics
# https://b-rodrigues.github.io/rix/articles/building-an-environment-for-literate-programming.html
rix(r_ver = "4.3.1",
    r_pkgs = c("quarto", "MASS"),
    system_pkgs = "quarto",
    tex_pkgs = c(
      "amsmath",
      "environ",
      "fontawesome5",
      "orcidlink",
      "pdfcol",
      "tcolorbox",
      "tikzfill"
    ),
    ide = "other",
    shell_hook = "",
    project_path = path_default_nix,
    overwrite = TRUE,
    print = F)




# ----
rix(r_ver = "latest",
    r_pkgs = c("dplyr", "ggplot2"),
    system_pkgs = NULL,
    git_pkgs = NULL,
    ide = "code",
    project_path = path_default_nix,
    overwrite = TRUE)
